
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 23 17:11:02 COT 2020
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int WHERE = 30;
  public static final int FROM = 29;
  public static final int Parentesis_c = 15;
  public static final int KEY = 10;
  public static final int Parentesis_a = 14;
  public static final int SELECT = 28;
  public static final int Numero = 22;
  public static final int Comilla_s = 3;
  public static final int NOT = 33;
  public static final int Corchete_c = 19;
  public static final int Op_booleano = 13;
  public static final int ERROR = 23;
  public static final int Corchete_a = 18;
  public static final int Identificador = 8;
  public static final int Comillas = 2;
  public static final int Llave_c = 17;
  public static final int Coma = 21;
  public static final int Llave_a = 16;
  public static final int Op_relacional = 12;
  public static final int P_coma = 20;
  public static final int T_dato = 4;
  public static final int Asterisco = 24;
  public static final int CREATE = 5;
  public static final int INSERT = 25;
  public static final int EOF = 0;
  public static final int VALUES = 27;
  public static final int error = 1;
  public static final int Op_logico = 11;
  public static final int USE = 6;
  public static final int Igual = 31;
  public static final int DELETE = 32;
  public static final int Reservada = 7;
  public static final int NULL = 34;
  public static final int TIPO_KEY = 9;
  public static final int INTO = 26;
}

